version: '3.7'

services:
  lemonsaurus:
    image: heavysaturn/lemonsaurus:latest
    build:
      context: .
      dockerfile: docker/lemonsaurus.Dockerfile
    container_name: lemonsaurus
    restart: always
    ports:
      - 8002:8002
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./static/:/static/
      - ./lemonsaurus/:/lemonsaurus/
      - ./apps/:/apps/
