version: '3.7'

services:
  lemonsaurus:
    image: lemonsaurus/lemonsaurus:latest
    build:
      context: .
      dockerfile: docker/lemonsaurus.Dockerfile
    container_name: lemonsaurus
    restart: always
    ports:
      - 8002:8002
    env_file:
      - .env
    volumes:
      - ./static/:/static/
      - ./lemonsaurus/:/lemonsaurus/
      - ./apps/:/apps/
